name: Chiusura automatica issue senza log

on:
  issues:
    types: [opened, edited]

jobs:
  check-log:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Verifica presenza log
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const body = issue.body || '';
            
            // Cerca la sezione "Invia qui il tuo log:"
            const logSectionRegex = /###\s*Invia qui il tuo log:\s*```([\s\S]*?)```/i;
            const match = body.match(logSectionRegex);
            
            // Verifica se il log è presente e non è vuoto
            let hasValidLog = false;
            
            if (match && match[1]) {
              const logContent = match[1].trim();
              // Controlla che il log abbia almeno 50 caratteri (non sia solo spazi vuoti)
              hasValidLog = logContent.length > 50;
            }
            
            // Se il log non è valido, chiudi la issue
            if (!hasValidLog) {
              // Verifica se la issue è già stata chiusa automaticamente
              const comments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number
              });
              
              const alreadyWarned = comments.data.some(comment => 
                comment.body.includes('chiuso automaticamente') && 
                comment.user.type === 'Bot'
              );
              
              // Se non è stata già avvisata, commenta e chiudi
              if (!alreadyWarned) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: '⚠️ **Questo problema è stato chiuso automaticamente, in quanto non hai inviato il log richiesto.**\n\n' +
                        'Per riaprire questa issue:\n' +
                        '1. Ottieni il log seguendo le istruzioni: https://telegra.ph/LOG-11-20\n' +
                        '2. Clicca sui **[...]** in alto a destra → **Edit**\n' +
                        '3. Incolla il log completo nella sezione "Invia qui il tuo log:"\n' +
                        '4. Riapri manualmente la issue\n\n' +
                        'Grazie per la collaborazione! 🙏'
                });
                
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  labels: ['log-mancante']
                });
                
                console.log('Issue chiusa: log non presente o troppo breve');
              }
            } else {
              console.log('Issue valida: log presente');
              
              // Se la issue era stata chiusa per mancanza di log, rimuovi l'etichetta
              const labels = issue.labels.map(label => label.name);
              if (labels.includes('log-mancante')) {
                await github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  name: 'log-mancante'
                }).catch(() => {
                  // Ignora errori se l'etichetta non esiste
                });
              }
            }
